import requests
import feedparser

KEYWORDS = [
    'corvid', 'crow', 'raven', 'corvus', 'jay', 'magpie',
    'jackdaw', 'rook', 'chough', 'nutcracker'
]

def fetch_one_arxiv_example():
    query = " OR ".join(KEYWORDS)
    url = (
        "https://export.arxiv.org/api/query?"
        f"search_query=all:({query})&"
        "start=0&max_results=1&sortBy=lastUpdatedDate&sortOrder=descending"
    )

    response = requests.get(url)
    feed = feedparser.parse(response.text)

    if not feed.entries:
        return None

    entry = feed.entries[0]

    return {
        "title": entry.title,
        "abstract": entry.summary,
        "authors": [a.name for a in entry.authors],
        "published": entry.published,
        "link": entry.link,
    }

result = fetch_one_arxiv_example()
print(result)




# a quick test using teh above got me:
    
    
'D. M. Shangase',
'M. Shapkin',
'R. S. Sharma',
'I. Shchemerov',
'L. Shchutska',
'T. Shears',
'L. Shekhtman',
'Z. Shen',
'S. Sheng',
'V. Shevchenko',
'B. Shi',
'Q. Shi',
'Y. Shimizu',
'E. Shmanin',
'R. Shorkin',
'J. D. Shupperd',
'R. Silva Coutinho',
'G. Simi',
'S. Simone',
'N. Skidmore',
'T. Skwarnicki',
'M. W. Slater',
'J. C. Smallwood',
'E. Smith',
'K. Smith',
'M. Smith',
'A. Snoch',
'L. Soares Lavra',
'M. D. Sokoloff',
'F. J. P. Soler',
'A. Solomin',
'A. Solovev',
'I. Solovyev',
'N. S. Sommerfeld',
'R. Song',
'Y. Song',
'Y. Song',
'Y. S. Song',
'F. L. Souza De Almeida',
'B. Souza De Paula',
'E. Spadaro Norella',
'E. Spedicato',
'J. G. Speer',
'E. Spiridenkov',
'P. Spradlin',
'V. Sriskaran',
'F. Stagni',
'M. Stahl',
'S. Stahl',
'S. Stanislaus',
'E. N. Stein',
'O. Steinkamp',
'O. Stenyakin',
'H. Stevens',
'D. Strekalina',
'Y. Su',
'F. Suljik',
'J. Sun',
'L. Sun',
'D. Sundfeld',
'W. Sutcliffe',
'P. N. Swallow',
'K. Swientek',
'F. Swystun',
'A. Szabelski',
'T. Szumlak',
'Y. Tan',
'Y. Tang',
'M. D. Tat',
'A. Terentev',
'F. Terzuoli',
'F. Teubert',
'E. Thomas',
'D. J. D. Thompson',
'H. Tilquin',
'V. Tisserand',
"S. T'Jampens",
'M. Tobin',
'L. Tomassetti',
'G. Tonani',
'X. Tong',
'D. Torres Machado',
'L. Toscano',
'D. Y. Tou',
'C. Trippl',
'G. Tuci',
'N. Tuning',
'L. H. Uecker',
'A. Ukleja',
'D. J. Unverzagt',
'B. Urbach',
'E. Ursov',
'A. Usachov',
'A. Ustyuzhanin',
'U. Uwer',
'V. Vagnoni',
'V. Valcarce Cadenas',
'G. Valenti',
'N. Valls Canudas',
'H. Van Hecke',
'E. van Herwijnen',
'C. B. Van Hulse',
'R. Van Laak',
'M. van Veghel',
'G. Vasquez',
'R. Vazquez Gomez',
'P. Vazquez Regueiro',
'C. Vázquez Sierra',
'S. Vecchi',
'J. J. Velthuis',
'M. Veltri',
'A. Venkateswaran',
'M. Verdoglia',
'M. Vesterinen',
'D. Vico Benet',
'P. Vidrier Villalba',
'M. Vieites Diaz',
'X. Vilasis-Cardona',
'E. Vilella Figueras',
'A. Villa',
'P. Vincent',
'F. C. Volle',
'D. vom Bruch',
'N. Voropaev',
'K. Vos',
'C. Vrahas',
'J. Wagner',
'J. Walsh',
'E. J. Walton',
'G. Wan',
'C. Wang',
'G. Wang',
'H. Wang',
'J. Wang',
'J. Wang',
'J. Wang',
'J. Wang',
'M. Wang',
'N. W. Wang',
'R. Wang',
'X. Wang',
'X. Wang',
'X. W. Wang',
'Y. Wang',
'Y. W. Wang',
'Z. Wang',
'Z. Wang',
'Z. Wang',
'J. A. Ward',
'M. Waterlaat',
'N. K. Watson',
'D. Websdale',
'Y. Wei',
'J. Wendel',
'B. D. C. Westhenry',
'C. White',
'M. Whitehead',
'E. Whiter',
'A. R. Wiederhold',
'D. Wiedner',
'G. Wilkinson',
'M. K. Wilkinson',
'M. Williams',
'M. J. Williams',
'M. R. J. Williams',
'R. Williams',
'Z. Williams',
'F. F. Wilson',
'M. Winn',
'W. Wislicki',
'M. Witek',
'L. Witola',
'G. Wormser',
'S. A. Wotton',
'H. Wu',
'J. Wu',
'X. Wu',
'Y. Wu',
'Z. Wu',
'K. Wyllie',
'S. Xian',
'Z. Xiang',
'Y. Xie',
'A. Xu',
'J. Xu',
'L. Xu',
'L. Xu',
'M. Xu',
'Z. Xu',
'Z. Xu',
'Z. Xu',
'K. Yang',
'S. Yang',
'X. Yang',
'Y. Yang',
'Z. Yang',
'V. Yeroshenko',
'H. Yeung',
'H. Yin',
'X. Yin',
'C. Y. Yu',
'J. Yu',
'X. Yuan',
'Y Yuan',
'E. Zaffaroni',
'M. Zavertyaev',
'M. Zdybal',
'F. Zenesini',
'C. Zeng',
'M. Zeng',
'C. Zhang',
'D. Zhang',
'J. Zhang',
'L. Zhang',
'S. Zhang',
'S. Zhang',
'Y. Zhang',
'Y. Z. Zhang',
'Z. Zhang',
'Y. Zhao',
'A. Zharkova',
'A. Zhelezov',
'S. Z. Zheng',
'X. Z. Zheng',
'Y. Zheng',
'T. Zhou',
'X. Zhou',
'Y. Zhou',
'V. Zhovkovska',
'L. Z. Zhu',
'X. Zhu',
'X. Zhu',
'V. Zhukov',
'J. Zhuo',
'Q. Zou',
'D. Zuliani',
'G. Zunica'] , 
# 'published': '2024-11-08T16:15:18Z', 'link': 'https://arxiv.org/abs/2411.05669v2'}